import Head from 'next/head';
import Image from 'next/image';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Blom: Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main className="mt-14">
        <section className="flex justify-center mb-8">
          <Image src={'/programming.svg'} width={350} height={350} alt="prog" />
        </section>
        <section className="mb-14 ">
          <h1 className="text-3xl mb-8 font-semibold">
            Need to learn how to code?
          </h1>
          <h2 className="text-xl mb-6">
            Try Blom. The free source app that provides you with everything.
          </h2>
          <p className="text-lg mb-4">Click the button below</p>
          <button className="classic_button">Start yout journey</button>
        </section>
        <section className="p-6 relative -inset-x-8 w-screen bg-teal-500 text-white">
          <h1 className="text-3xl font-semibold">Why you should use Blom?</h1>
        </section>
      </main>
    </div>
  );
}
