import CardAnaly from 'components/CardAnaly';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { BiUserCircle } from 'react-icons/bi';
import { DiCodepen } from 'react-icons/di';
import { AiOutlineStock } from 'react-icons/ai';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blom: Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main className="mt-14">
        <section className="flex justify-center mb-8">
          <Image src={'/programming.svg'} width={350} height={350} alt="prog" />
        </section>
        <section className="mb-14 ">
          <h1 className="text-3xl mb-8 font-semibold">
            Need to learn how to code?
          </h1>
          <h2 className="text-xl mb-6">
            Try Blom. The free source app that provides you with everything.
          </h2>
          <p className="text-lg mb-4">Click the button below</p>
          <Link className="classic_button" href={'/auth/login'}>
            Start yout journey
          </Link>
        </section>
        <section className="p-8 relative -inset-x-8 w-screen bg-teal-500 text-white">
          <h1 className="text-3xl font-semibold mb-7">
            Why you should use Blom?
          </h1>
          <div>
            <p className="text-lg mb-8">
              Blom is a safe to use platform for learning how to code!
            </p>
            <div className="flex justify-center items-center flex-wrap gap-4">
              <CardAnaly>
                <BiUserCircle className="w-8 h-8" />
                <span className="text-gray-800">+3000 users</span>
              </CardAnaly>
              <CardAnaly>
                <AiOutlineStock className="w-8 h-8" />
                <span className="text-gray-800">+20% in value</span>
              </CardAnaly>
              <CardAnaly>
                <DiCodepen className="w-8 h-8" />
                <span className="text-gray-800">+2000 lines writen</span>
              </CardAnaly>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
