import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main className="mt-14">
        <div className="flex  justify-center mb-8">
          <Image src={'/programming.svg'} width={350} height={350} alt="prog" />
        </div>
        <div>
          <h1 className="text-3xl mb-6">Need to learn how to code?</h1>
          <h2 className="text-xl mb-4">
            Try Blom. The free source app that provides you with everything.
          </h2>
          <p className="text-lg mb-4">Click the button below</p>
          <button className="py-2 px-4 text-lg bg-teal-400 text-white rounded-lg font-semibold hover:bg-gray-800 transition-all ease-linear duration-100">
            Start yout journey
          </button>
        </div>
      </main>
    </div>
  );
}
